update libc crate to >=0.2.187
this is needed to compile on 32-bit architectures with 64-bit time_t
now; libc 0.2.186 fails with:

	error: cannot construct `timespec` with struct literal syntax due to private fields
	   --> /builds/alpine/aports/community/kubie/tmp/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/interprocess-2.4.0/src/os/unix/c_wrappers.rs:435:8
	    |
	435 |     Ok(libc::timespec { tv_sec, tv_nsec: d.subsec_nanos() as _ })
	    |        ^^^^^^^^^^^^^^
	    |
	    = note: ...and other private field `__pad0` that was not provided
	help: consider using the `Default` trait
	    |
	435 -     Ok(libc::timespec { tv_sec, tv_nsec: d.subsec_nanos() as _ })
	435 +     Ok(<libc::timespec as std::default::Default>::default())
	    |

Link: https://github.com/rust-lang/libc/releases/tag/0.2.187
Link: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/106102